// <auto-generated />
namespace OKVGU.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Change_type_Amount_SubjectSemester : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_type_Amount_SubjectSemester));
        
        string IMigrationMetadata.Id
        {
            get { return "202105200952371_Change_type_Amount_SubjectSemester"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
